SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `siec`.`tr_evaluacion_parcial` DROP FOREIGN KEY `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1` , DROP FOREIGN KEY `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1` , DROP FOREIGN KEY `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1` , DROP FOREIGN KEY `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1` ;

ALTER TABLE `siec`.`tr_maestro_materia_grupo_sesion` DROP FOREIGN KEY `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1` ;

ALTER TABLE `siec`.`tr_maestro_materia_grupo` DROP FOREIGN KEY `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1` ;

ALTER TABLE `siec`.`tr_maestro_materia` DROP FOREIGN KEY `fk_TR_MAESTRO_MATERIA_TC_MATERIAS` , DROP FOREIGN KEY `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1` ;

ALTER TABLE `siec`.`tc_grupo` DROP FOREIGN KEY `fk_TC_GRUPO_TC_CARRERA1` ;

ALTER TABLE `siec`.`tc_materias` DROP FOREIGN KEY `fk_MATERIAS_TC_DEPARTAMENTOS1` ;

ALTER TABLE `siec`.`tr_maestros` DROP FOREIGN KEY `fk_MAESTROS_TR_USUARIO1` ;

ALTER TABLE `siec`.`tr_sesion` DROP FOREIGN KEY `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` , DROP FOREIGN KEY `fk_TR_SESION_TR_SESION_RECHAZADA1` ;

CREATE  TABLE IF NOT EXISTS `siec`.`TC_GRUPO` (
  `GRUPO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_GRUPO` VARCHAR(45) NULL DEFAULT NULL ,
  `CARRERA_ID` INT(11) NOT NULL ,
  `CUATRIMESTRE` VARCHAR(45) NULL DEFAULT NULL ,
  `LETRA` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`GRUPO_ID`) ,
  INDEX `fk_TC_GRUPO_TC_CARRERA1` (`CARRERA_ID` ASC) ,
  CONSTRAINT `fk_TC_GRUPO_TC_CARRERA1`
    FOREIGN KEY (`CARRERA_ID` )
    REFERENCES `siec`.`TC_CARRERA` (`CARRERA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TC_MATERIAS` (
  `MATERIAS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_MATERIAS` VARCHAR(45) NULL DEFAULT NULL ,
  `DEPARTAMENTO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MATERIAS_ID`) ,
  INDEX `fk_MATERIAS_TC_DEPARTAMENTOS1` (`DEPARTAMENTO_ID` ASC) ,
  CONSTRAINT `fk_MATERIAS_TC_DEPARTAMENTOS1`
    FOREIGN KEY (`DEPARTAMENTO_ID` )
    REFERENCES `siec`.`TC_DEPARTAMENTOS` (`DEPARTAMENTO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TR_ESTRATEGIAS` (
  `ESTRATEGIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FECHA_INICIO_REGISTRO` DATE NULL DEFAULT NULL ,
  `MENSAJE` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTRO_ID` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTROS_MAESTRO_ID` INT(11) NOT NULL ,
  `EVALUACION_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ESTRATEGIA_ID`) ,
  INDEX `fk_TR_ESTRATEGIAS_MAESTROS1` (`MAESTROS_MAESTRO_ID` ASC) ,
  CONSTRAINT `fk_TR_ESTRATEGIAS_MAESTROS1`
    FOREIGN KEY (`MAESTROS_MAESTRO_ID` )
    REFERENCES `siec`.`TR_MAESTROS` (`MAESTRO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TR_EVALUACION_ACUMULATIVA` (
  `EVALUACION_ACUMULATIVA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PARCIAL` INT(11) NULL DEFAULT NULL ,
  `CALIFICACION` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`EVALUACION_ACUMULATIVA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TR_EVALUACION_PARCIAL_ACUMULATIVA` (
  `EVALUACION_PARCIAL_ACUMULATIVA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `EVALUACION_PARCIAL_ID` INT(11) NOT NULL ,
  `EVALUACION_ACUMULATIVA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`EVALUACION_PARCIAL_ACUMULATIVA_ID`) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_PARCIAL1` (`EVALUACION_PARCIAL_ID` ASC) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_ACUMULATIVA1` (`EVALUACION_ACUMULATIVA_ID` ASC) ,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_PARCIAL1`
    FOREIGN KEY (`EVALUACION_PARCIAL_ID` )
    REFERENCES `siec`.`TR_EVALUACION_PARCIAL` (`EVALUACION_PARCIAL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_ACUMULATIVA1`
    FOREIGN KEY (`EVALUACION_ACUMULATIVA_ID` )
    REFERENCES `siec`.`TR_EVALUACION_ACUMULATIVA` (`EVALUACION_ACUMULATIVA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TR_MAESTROS` (
  `MAESTRO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `CODIGO` VARCHAR(45) NULL DEFAULT NULL ,
  `USUARIO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MAESTRO_ID`) ,
  INDEX `fk_MAESTROS_TR_USUARIO1` (`USUARIO_ID` ASC) ,
  CONSTRAINT `fk_MAESTROS_TR_USUARIO1`
    FOREIGN KEY (`USUARIO_ID` )
    REFERENCES `siec`.`TR_USUARIO` (`USUARIO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

CREATE  TABLE IF NOT EXISTS `siec`.`TR_SESION` (
  `SESION_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MENSAJE` VARCHAR(255) NULL DEFAULT NULL ,
  `ESTADO` INT(11) NULL DEFAULT NULL ,
  `CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL ,
  `SESION_RECHAZADA_ID` INT(11) NOT NULL ,
  `PONDERACION` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`SESION_ID`) ,
  INDEX `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` (`CRITERIO_COMPETENCIA_ID` ASC) ,
  INDEX `fk_TR_SESION_TR_SESION_RECHAZADA1` (`SESION_RECHAZADA_ID` ASC) ,
  CONSTRAINT `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1`
    FOREIGN KEY (`CRITERIO_COMPETENCIA_ID` )
    REFERENCES `siec`.`TR_CRITERIO_COMPETENCIA` (`CRITERIO_COMPETENCIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_SESION_TR_SESION_RECHAZADA1`
    FOREIGN KEY (`SESION_RECHAZADA_ID` )
    REFERENCES `siec`.`TR_SESION_RECHAZADA` (`SESION_RECHAZADA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

ALTER TABLE `siec`.`tr_evaluacion_parcial` DROP COLUMN `ALUMNOS_ID` , DROP COLUMN `EVALUACION_NIVEL_ID` , DROP COLUMN `MAESTRO_MATERIA_GRUPO_SESION_ID` , DROP COLUMN `TIPO_EVALUACION_ID` , ADD COLUMN `CALIFICACION` INT(11) NULL DEFAULT NULL  AFTER `EVALUACION_PARCIAL_ID` , ADD COLUMN `EVALUACION_NIVEL_ID` INT(11) NOT NULL  AFTER `PARCIAL` , ADD COLUMN `TIPO_EVALUACION_ID` INT(11) NOT NULL  AFTER `EVALUACION_NIVEL_ID` , ADD COLUMN `ALUMNOS_ID` INT(11) NOT NULL  AFTER `TIPO_EVALUACION_ID` , ADD COLUMN `MAESTRO_MATERIA_GRUPO_SESION_ID` INT(11) NOT NULL  AFTER `TIPO_EVALUACION_ID` , 
  ADD CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1`
  FOREIGN KEY (`EVALUACION_NIVEL_ID` )
  REFERENCES `siec`.`TC_EVALUACION_NIVEL` (`EVALUACION_NIVEL_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1`
  FOREIGN KEY (`TIPO_EVALUACION_ID` )
  REFERENCES `siec`.`TC_TIPO_EVALUACION` (`TIPO_EVALUACION_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1`
  FOREIGN KEY (`MAESTRO_MATERIA_GRUPO_SESION_ID` )
  REFERENCES `siec`.`TR_MAESTRO_MATERIA_GRUPO_SESION` (`MAESTRO_MATERIA_GRUPO_SESION_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1`
  FOREIGN KEY (`ALUMNOS_ID` )
  REFERENCES `siec`.`TR_ALUMNOS` (`ALUMNOS_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP INDEX `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1` 
, ADD INDEX `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1` (`EVALUACION_NIVEL_ID` ASC) 
, DROP INDEX `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1` 
, ADD INDEX `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1` (`TIPO_EVALUACION_ID` ASC) 
, DROP INDEX `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1` 
, ADD INDEX `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1` (`MAESTRO_MATERIA_GRUPO_SESION_ID` ASC) 
, DROP INDEX `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1` 
, ADD INDEX `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1` (`ALUMNOS_ID` ASC) ;

ALTER TABLE `siec`.`tr_maestro_materia_grupo_sesion` DROP COLUMN `MAE_MAT_GRP_ID` , ADD COLUMN `MAE_MAT_GRP_ID` INT(11) NOT NULL  AFTER `SESION_SESION_ID` , 
  ADD CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1`
  FOREIGN KEY (`MAE_MAT_GRP_ID` )
  REFERENCES `siec`.`TR_MAESTRO_MATERIA_GRUPO` (`MAESTRO_MATERIA_GRUPO_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1` 
, ADD INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1` (`MAE_MAT_GRP_ID` ASC) ;

ALTER TABLE `siec`.`tr_maestro_materia_grupo` DROP COLUMN `MAESTRO_MATERIA_ID` , ADD COLUMN `MAESTRO_MATERIA_ID` INT(11) NOT NULL  AFTER `GRUPO_GRUPO_ID` , 
  ADD CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1`
  FOREIGN KEY (`MAESTRO_MATERIA_ID` )
  REFERENCES `siec`.`TR_MAESTRO_MATERIA` (`MAESTRO_MATERIA_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1` 
, ADD INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1` (`MAESTRO_MATERIA_ID` ASC) ;

ALTER TABLE `siec`.`tr_maestro_materia` DROP COLUMN `MAESTRO_ID` , DROP COLUMN `MATERIAS_ID` , ADD COLUMN `MAESTRO_ID` INT(11) NOT NULL  AFTER `MAESTRO_MATERIA_ID` , ADD COLUMN `MATERIAS_ID` INT(11) NOT NULL  AFTER `MAESTRO_MATERIA_ID` , 
  ADD CONSTRAINT `fk_TR_MAESTRO_MATERIA_TC_MATERIAS`
  FOREIGN KEY (`MATERIAS_ID` )
  REFERENCES `siec`.`TC_MATERIAS` (`MATERIAS_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1`
  FOREIGN KEY (`MAESTRO_ID` )
  REFERENCES `siec`.`TR_MAESTROS` (`MAESTRO_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP INDEX `fk_TR_MAESTRO_MATERIA_TC_MATERIAS` 
, ADD INDEX `fk_TR_MAESTRO_MATERIA_TC_MATERIAS` (`MATERIAS_ID` ASC) 
, DROP INDEX `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1` 
, ADD INDEX `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1` (`MAESTRO_ID` ASC) ;

ALTER TABLE `siec`.`tr_estrategias` 
  ADD CONSTRAINT `fk_TR_ESTRATEGIAS_TC_EVALUACION1`
  FOREIGN KEY (`EVALUACION_ID` )
  REFERENCES `siec`.`tr_evaluacion` (`EVALUACION_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_TR_ESTRATEGIAS_TC_EVALUACION1` (`EVALUACION_ID` ASC) ;

ALTER TABLE `siec`.`tr_sesion` DROP COLUMN `CRITERIO_COMPETENCIA_ID` , DROP COLUMN `SESION_RECHAZADA_ID` , ADD COLUMN `CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL  AFTER `ESTADO` , ADD COLUMN `SESION_RECHAZADA_SESION_RECHAZADA_ID` INT(11) NOT NULL  AFTER `CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` 
, DROP INDEX `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` 
, ADD INDEX `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` (`CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` ASC) 
, DROP INDEX `fk_TR_SESION_TR_SESION_RECHAZADA1` 
, ADD INDEX `fk_TR_SESION_TR_SESION_RECHAZADA1` (`SESION_RECHAZADA_SESION_RECHAZADA_ID` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
