SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `siec` DEFAULT CHARACTER SET latin1 ;
USE `siec` ;

-- -----------------------------------------------------
-- Table `siec`.`TC_CATEGORIAS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_categorias` (
  `CATEGORIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CATEGORIA` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `ORDEN` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`CATEGORIA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_COMPETENCIAS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_competencias` (
  `COMPETENCIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_COMPETENCIA` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `CATEGORIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`COMPETENCIA_ID`) ,
  INDEX `fk_TC_COMPETENCIAS_CATEGORIAS` (`CATEGORIA_ID` ASC) ,
  CONSTRAINT `fk_TC_COMPETENCIAS_CATEGORIAS`
    FOREIGN KEY (`CATEGORIA_ID` )
    REFERENCES `siec`.`tc_categorias` (`CATEGORIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_CRITERIOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_criterios` (
  `CRITERIO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CRITERIO` VARCHAR(50) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (`CRITERIO_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_CRITERIO_COMPETENCIA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_criterio_competencia` (
  `CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PONDERACION_CRITERIO` VARCHAR(45) NULL DEFAULT NULL ,
  `CRITERIO_ID` INT(11) NOT NULL ,
  `COMPETENCIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`CRITERIO_COMPETENCIA_ID`) ,
  INDEX `fk_TR_CRITERIO_COMPETENCIA_TC_CRITERIOS1` (`CRITERIO_ID` ASC) ,
  INDEX `fk_TR_CRITERIO_COMPETENCIA_TC_COMPETENCIAS1` (`COMPETENCIA_ID` ASC) ,
  CONSTRAINT `fk_TR_CRITERIO_COMPETENCIA_TC_CRITERIOS1`
    FOREIGN KEY (`CRITERIO_ID` )
    REFERENCES `siec`.`tc_criterios` (`CRITERIO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_CRITERIO_COMPETENCIA_TC_COMPETENCIAS1`
    FOREIGN KEY (`COMPETENCIA_ID` )
    REFERENCES `siec`.`tc_competencias` (`COMPETENCIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_PERFIL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_perfil` (
  `PERFIL_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_PERFIL` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`PERFIL_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_USUARIO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_usuario` (
  `USUARIO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NOMBRES` VARCHAR(45) NULL DEFAULT NULL ,
  `APELLIDOS` VARCHAR(45) NULL DEFAULT NULL ,
  `FECHA_NAC` DATE NULL DEFAULT NULL ,
  `USUARIO` VARCHAR(45) NULL DEFAULT NULL ,
  `PASSWORD` VARCHAR(45) NULL DEFAULT NULL ,
  `PERFIL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`USUARIO_ID`) ,
  INDEX `fk_USUARIO_PERFIL1` (`PERFIL_ID` ASC) ,
  CONSTRAINT `fk_USUARIO_PERFIL1`
    FOREIGN KEY (`PERFIL_ID` )
    REFERENCES `siec`.`tc_perfil` (`PERFIL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_CARRERA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_carrera` (
  `CARRERA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CARRERA` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`CARRERA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_GRUPO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_grupo` (
  `GRUPO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_GRUPO` VARCHAR(45) NULL DEFAULT NULL ,
  `CARRERA_ID` INT(11) NOT NULL ,
  `CUATRIMESTRE` VARCHAR(45) NULL DEFAULT NULL ,
  `LETRA` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`GRUPO_ID`) ,
  INDEX `fk_TC_GRUPO_TC_CARRERA1` (`CARRERA_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_ALUMNOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_alumnos` (
  `ALUMNOS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MATRICULA` VARCHAR(45) NULL DEFAULT NULL ,
  `USUARIO_ID` INT(11) NOT NULL ,
  `GRUPO_ID` INT(11) NOT NULL ,
  `CARRERA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ALUMNOS_ID`) ,
  INDEX `fk_TC_ALUMNOS_TC_USUARIO1` (`USUARIO_ID` ASC) ,
  INDEX `fk_TR_ALUMNOS_TC_GRUPO1` (`GRUPO_ID` ASC) ,
  INDEX `fk_TR_ALUMNOS_TC_CARRERA1` (`CARRERA_ID` ASC) ,
  CONSTRAINT `fk_TC_ALUMNOS_TC_USUARIO1`
    FOREIGN KEY (`USUARIO_ID` )
    REFERENCES `siec`.`tr_usuario` (`USUARIO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ALUMNOS_TC_GRUPO1`
    FOREIGN KEY (`GRUPO_ID` )
    REFERENCES `siec`.`tc_grupo` (`GRUPO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ALUMNOS_TC_CARRERA1`
    FOREIGN KEY (`CARRERA_ID` )
    REFERENCES `siec`.`tc_carrera` (`CARRERA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_REPORTES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_reportes` (
  `REPORTES_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_REPORTES` VARCHAR(45) NULL DEFAULT NULL ,
  `PERFIL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`REPORTES_ID`) ,
  INDEX `fk_TC_REPORTES_TC_PERFIL1` (`PERFIL_ID` ASC) ,
  CONSTRAINT `fk_TC_REPORTES_TC_PERFIL1`
    FOREIGN KEY (`PERFIL_ID` )
    REFERENCES `siec`.`tc_perfil` (`PERFIL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_DEPARTAMENTOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_departamentos` (
  `DEPARTAMENTO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_DEPARTAMENTO` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`DEPARTAMENTO_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_MATERIAS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_materias` (
  `MATERIAS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_MATERIAS` VARCHAR(45) NULL DEFAULT NULL ,
  `DEPARTAMENTO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MATERIAS_ID`) ,
  INDEX `fk_MATERIAS_TC_DEPARTAMENTOS1` (`DEPARTAMENTO_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_MAESTROS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_maestros` (
  `MAESTRO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `CODIGO` VARCHAR(45) NULL DEFAULT NULL ,
  `USUARIO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MAESTRO_ID`) ,
  INDEX `fk_MAESTROS_TR_USUARIO1` (`USUARIO_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_ESTRATEGIAS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_estrategias` (
  `ESTRATEGIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FECHA_INICIO_REGISTRO` DATE NULL DEFAULT NULL ,
  `MENSAJE` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTRO_ID` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTROS_MAESTRO_ID` INT(11) NOT NULL ,
  `EVALUACION_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ESTRATEGIA_ID`) ,
  INDEX `fk_TR_ESTRATEGIAS_MAESTROS1` (`MAESTROS_MAESTRO_ID` ASC) ,
  INDEX `fk_TR_ESTRATEGIAS_TC_EVALUACION1` (`EVALUACION_ID` ASC) ,
  CONSTRAINT `fk_TR_ESTRATEGIAS_MAESTROS1`
    FOREIGN KEY (`MAESTROS_MAESTRO_ID` )
    REFERENCES `siec`.`tr_maestros` (`MAESTRO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ESTRATEGIAS_TC_EVALUACION1`
    FOREIGN KEY (`EVALUACION_ID` )
    REFERENCES `siec`.`tr_evaluacion` (`EVALUACION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_COMENTARIO_DPA_ESTRATEGIA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_comentario_dpa_estrategia` (
  `COMENT_ESTRA_DPA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `ESTRATEGIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`COMENT_ESTRA_DPA_ID`) ,
  INDEX `fk_TR_COMENTARIO_DPA_ESTRATEGIA_TR_ESTRATEGIAS1` (`ESTRATEGIA_ID` ASC) ,
  CONSTRAINT `fk_TR_COMENTARIO_DPA_ESTRATEGIA_TR_ESTRATEGIAS1`
    FOREIGN KEY (`ESTRATEGIA_ID` )
    REFERENCES `siec`.`tr_estrategias` (`ESTRATEGIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TC_EVALUACION_NIVEL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_evaluacion_nivel` (
  `EVALUACION_NIVEL_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_EVALUACION` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`EVALUACION_NIVEL_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_SESION_RECHAZADA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_sesion_rechazada` (
  `SESION_RECHAZADA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MENSAJE` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`SESION_RECHAZADA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_SESION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_sesion` (
  `SESION_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MENSAJE` VARCHAR(255) NULL DEFAULT NULL ,
  `ESTADO` INT(11) NULL DEFAULT NULL ,
  `CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL ,
  `SESION_RECHAZADA_SESION_RECHAZADA_ID` INT(11) NOT NULL ,
  `PONDERACION` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`SESION_ID`) ,
  INDEX `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` (`CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` ASC) ,
  INDEX `fk_TR_SESION_TR_SESION_RECHAZADA1` (`SESION_RECHAZADA_SESION_RECHAZADA_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_carrera`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_carrera` (
  `CARRERA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CARRERA` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`CARRERA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_categorias`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_categorias` (
  `CATEGORIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CATEGORIA` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `ORDEN` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`CATEGORIA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_competencias`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_competencias` (
  `COMPETENCIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_COMPETENCIA` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `CATEGORIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`COMPETENCIA_ID`) ,
  INDEX `fk_TC_COMPETENCIAS_CATEGORIAS` (`CATEGORIA_ID` ASC) ,
  CONSTRAINT `fk_TC_COMPETENCIAS_CATEGORIAS`
    FOREIGN KEY (`CATEGORIA_ID` )
    REFERENCES `siec`.`tc_categorias` (`CATEGORIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_criterios`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_criterios` (
  `CRITERIO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_CRITERIO` VARCHAR(50) NULL DEFAULT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (`CRITERIO_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_departamentos`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_departamentos` (
  `DEPARTAMENTO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_DEPARTAMENTO` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`DEPARTAMENTO_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_evaluacion_nivel`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_evaluacion_nivel` (
  `EVALUACION_NIVEL_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_EVALUACION` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`EVALUACION_NIVEL_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_grupo`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_grupo` (
  `GRUPO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_GRUPO` VARCHAR(45) NULL DEFAULT NULL ,
  `CARRERA_ID` INT(11) NOT NULL ,
  `CUATRIMESTRE` VARCHAR(45) NULL DEFAULT NULL ,
  `LETRA` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`GRUPO_ID`) ,
  INDEX `fk_TC_GRUPO_TC_CARRERA1` (`CARRERA_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_materias`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_materias` (
  `MATERIAS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_MATERIAS` VARCHAR(45) NULL DEFAULT NULL ,
  `DEPARTAMENTO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MATERIAS_ID`) ,
  INDEX `fk_MATERIAS_TC_DEPARTAMENTOS1` (`DEPARTAMENTO_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_perfil`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_perfil` (
  `PERFIL_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_PERFIL` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`PERFIL_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tc_reportes`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tc_reportes` (
  `REPORTES_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DES_REPORTES` VARCHAR(45) NULL DEFAULT NULL ,
  `PERFIL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`REPORTES_ID`) ,
  INDEX `fk_TC_REPORTES_TC_PERFIL1` (`PERFIL_ID` ASC) ,
  CONSTRAINT `fk_TC_REPORTES_TC_PERFIL1`
    FOREIGN KEY (`PERFIL_ID` )
    REFERENCES `siec`.`tc_perfil` (`PERFIL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_usuario`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_usuario` (
  `USUARIO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NOMBRES` VARCHAR(45) NULL DEFAULT NULL ,
  `APELLIDOS` VARCHAR(45) NULL DEFAULT NULL ,
  `FECHA_NAC` DATE NULL DEFAULT NULL ,
  `USUARIO` VARCHAR(45) NULL DEFAULT NULL ,
  `PASSWORD` VARCHAR(45) NULL DEFAULT NULL ,
  `PERFIL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`USUARIO_ID`) ,
  INDEX `fk_USUARIO_PERFIL1` (`PERFIL_ID` ASC) ,
  CONSTRAINT `fk_USUARIO_PERFIL1`
    FOREIGN KEY (`PERFIL_ID` )
    REFERENCES `siec`.`tc_perfil` (`PERFIL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_alumnos`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_alumnos` (
  `ALUMNOS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MATRICULA` VARCHAR(45) NULL DEFAULT NULL ,
  `USUARIO_ID` INT(11) NOT NULL ,
  `GRUPO_ID` INT(11) NOT NULL ,
  `CARRERA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ALUMNOS_ID`) ,
  INDEX `fk_TC_ALUMNOS_TC_USUARIO1` (`USUARIO_ID` ASC) ,
  INDEX `fk_TR_ALUMNOS_TC_GRUPO1` (`GRUPO_ID` ASC) ,
  INDEX `fk_TR_ALUMNOS_TC_CARRERA1` (`CARRERA_ID` ASC) ,
  CONSTRAINT `fk_TC_ALUMNOS_TC_USUARIO1`
    FOREIGN KEY (`USUARIO_ID` )
    REFERENCES `siec`.`tr_usuario` (`USUARIO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ALUMNOS_TC_GRUPO1`
    FOREIGN KEY (`GRUPO_ID` )
    REFERENCES `siec`.`tc_grupo` (`GRUPO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ALUMNOS_TC_CARRERA1`
    FOREIGN KEY (`CARRERA_ID` )
    REFERENCES `siec`.`tc_carrera` (`CARRERA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_maestros`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_maestros` (
  `MAESTRO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `CODIGO` VARCHAR(45) NULL DEFAULT NULL ,
  `USUARIO_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`MAESTRO_ID`) ,
  INDEX `fk_MAESTROS_TR_USUARIO1` (`USUARIO_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_estrategias`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_estrategias` (
  `ESTRATEGIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FECHA_INICIO_REGISTRO` DATE NULL DEFAULT NULL ,
  `MENSAJE` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTRO_ID` VARCHAR(45) NULL DEFAULT NULL ,
  `MAESTROS_MAESTRO_ID` INT(11) NOT NULL ,
  `EVALUACION_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ESTRATEGIA_ID`) ,
  INDEX `fk_TR_ESTRATEGIAS_MAESTROS1` (`MAESTROS_MAESTRO_ID` ASC) ,
  INDEX `fk_TR_ESTRATEGIAS_TC_EVALUACION1` (`EVALUACION_ID` ASC) ,
  CONSTRAINT `fk_TR_ESTRATEGIAS_MAESTROS1`
    FOREIGN KEY (`MAESTROS_MAESTRO_ID` )
    REFERENCES `siec`.`tr_maestros` (`MAESTRO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_ESTRATEGIAS_TC_EVALUACION1`
    FOREIGN KEY (`EVALUACION_ID` )
    REFERENCES `siec`.`tr_evaluacion` (`EVALUACION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_comentario_dpa_estrategia`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_comentario_dpa_estrategia` (
  `COMENT_ESTRA_DPA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `ESTRATEGIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`COMENT_ESTRA_DPA_ID`) ,
  INDEX `fk_TR_COMENTARIO_DPA_ESTRATEGIA_TR_ESTRATEGIAS1` (`ESTRATEGIA_ID` ASC) ,
  CONSTRAINT `fk_TR_COMENTARIO_DPA_ESTRATEGIA_TR_ESTRATEGIAS1`
    FOREIGN KEY (`ESTRATEGIA_ID` )
    REFERENCES `siec`.`tr_estrategias` (`ESTRATEGIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_criterio_competencia`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_criterio_competencia` (
  `CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PONDERACION_CRITERIO` VARCHAR(45) NULL DEFAULT NULL ,
  `CRITERIO_ID` INT(11) NOT NULL ,
  `COMPETENCIA_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`CRITERIO_COMPETENCIA_ID`) ,
  INDEX `fk_TR_CRITERIO_COMPETENCIA_TC_CRITERIOS1` (`CRITERIO_ID` ASC) ,
  INDEX `fk_TR_CRITERIO_COMPETENCIA_TC_COMPETENCIAS1` (`COMPETENCIA_ID` ASC) ,
  CONSTRAINT `fk_TR_CRITERIO_COMPETENCIA_TC_CRITERIOS1`
    FOREIGN KEY (`CRITERIO_ID` )
    REFERENCES `siec`.`tc_criterios` (`CRITERIO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_CRITERIO_COMPETENCIA_TC_COMPETENCIAS1`
    FOREIGN KEY (`COMPETENCIA_ID` )
    REFERENCES `siec`.`tc_competencias` (`COMPETENCIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_sesion`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_sesion` (
  `SESION_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MENSAJE` VARCHAR(255) NULL DEFAULT NULL ,
  `ESTADO` INT(11) NULL DEFAULT NULL ,
  `CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` INT(11) NOT NULL ,
  `SESION_RECHAZADA_SESION_RECHAZADA_ID` INT(11) NOT NULL ,
  `PONDERACION` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`SESION_ID`) ,
  INDEX `fk_TR_SESION_TR_CRITERIO_COMPETENCIA1` (`CRITERIO_COMPETENCIA_CRITERIO_COMPETENCIA_ID` ASC) ,
  INDEX `fk_TR_SESION_TR_SESION_RECHAZADA1` (`SESION_RECHAZADA_SESION_RECHAZADA_ID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`tr_sesion_rechazada`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`tr_sesion_rechazada` (
  `SESION_RECHAZADA_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MENSAJE` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`SESION_RECHAZADA_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siec`.`TR_MAESTRO_MATERIA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_MAESTRO_MATERIA` (
  `MAESTRO_MATERIA_ID` INT NOT NULL AUTO_INCREMENT ,
  `MATERIAS_ID` INT NOT NULL ,
  `MAESTRO_ID` INT NOT NULL ,
  PRIMARY KEY (`MAESTRO_MATERIA_ID`) ,
  INDEX `fk_TR_MAESTRO_MATERIA_TC_MATERIAS` (`MATERIAS_ID` ASC) ,
  INDEX `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1` (`MAESTRO_ID` ASC) ,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_TC_MATERIAS`
    FOREIGN KEY (`MATERIAS_ID` )
    REFERENCES `siec`.`TC_MATERIAS` (`MATERIAS_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_TR_MAESTROS1`
    FOREIGN KEY (`MAESTRO_ID` )
    REFERENCES `siec`.`TR_MAESTROS` (`MAESTRO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TR_MAESTRO_MATERIA_GRUPO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_MAESTRO_MATERIA_GRUPO` (
  `MAESTRO_MATERIA_GRUPO_ID` INT NOT NULL AUTO_INCREMENT ,
  `GRUPO_GRUPO_ID` INT NOT NULL ,
  `MAESTRO_MATERIA_ID` INT NOT NULL ,
  PRIMARY KEY (`MAESTRO_MATERIA_GRUPO_ID`) ,
  INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_TC_GRUPO1` (`GRUPO_GRUPO_ID` ASC) ,
  INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1` (`MAESTRO_MATERIA_ID` ASC) ,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_TC_GRUPO1`
    FOREIGN KEY (`GRUPO_GRUPO_ID` )
    REFERENCES `siec`.`TC_GRUPO` (`GRUPO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_TR_MAESTRO_MATERIA1`
    FOREIGN KEY (`MAESTRO_MATERIA_ID` )
    REFERENCES `siec`.`TR_MAESTRO_MATERIA` (`MAESTRO_MATERIA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TR_MAESTRO_MATERIA_GRUPO_SESION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_MAESTRO_MATERIA_GRUPO_SESION` (
  `MAESTRO_MATERIA_GRUPO_SESION_ID` INT NOT NULL AUTO_INCREMENT ,
  `SESION_SESION_ID` INT NOT NULL ,
  `MAE_MAT_GRP_ID` INT NOT NULL ,
  PRIMARY KEY (`MAESTRO_MATERIA_GRUPO_SESION_ID`) ,
  INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_SESION1` (`SESION_SESION_ID` ASC) ,
  INDEX `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1` (`MAE_MAT_GRP_ID` ASC) ,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_SESION1`
    FOREIGN KEY (`SESION_SESION_ID` )
    REFERENCES `siec`.`TR_SESION` (`SESION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_MAESTRO_MATERIA_GRUPO_SESION_TR_MAESTRO_MATERIA_GRUPO1`
    FOREIGN KEY (`MAE_MAT_GRP_ID` )
    REFERENCES `siec`.`TR_MAESTRO_MATERIA_GRUPO` (`MAESTRO_MATERIA_GRUPO_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TC_TIPO_EVALUACION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TC_TIPO_EVALUACION` (
  `TIPO_EVALUACION_ID` INT NOT NULL AUTO_INCREMENT ,
  `DES_TIPO_EVALUACION` VARCHAR(45) NULL ,
  PRIMARY KEY (`TIPO_EVALUACION_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TR_EVALUACION_PARCIAL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_EVALUACION_PARCIAL` (
  `EVALUACION_PARCIAL_ID` INT NOT NULL AUTO_INCREMENT ,
  `CALIFICACION` INT NULL ,
  `PARCIAL` INT NULL ,
  `EVALUACION_NIVEL_ID` INT NOT NULL ,
  `TIPO_EVALUACION_ID` INT NOT NULL ,
  `MAESTRO_MATERIA_GRUPO_SESION_ID` INT NOT NULL ,
  `ALUMNOS_ID` INT NOT NULL ,
  PRIMARY KEY (`EVALUACION_PARCIAL_ID`) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1` (`EVALUACION_NIVEL_ID` ASC) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1` (`TIPO_EVALUACION_ID` ASC) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1` (`MAESTRO_MATERIA_GRUPO_SESION_ID` ASC) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1` (`ALUMNOS_ID` ASC) ,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TC_EVALUACION_NIVEL1`
    FOREIGN KEY (`EVALUACION_NIVEL_ID` )
    REFERENCES `siec`.`TC_EVALUACION_NIVEL` (`EVALUACION_NIVEL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TC_TIPO_EVALUACION1`
    FOREIGN KEY (`TIPO_EVALUACION_ID` )
    REFERENCES `siec`.`TC_TIPO_EVALUACION` (`TIPO_EVALUACION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TR_MAESTRO_MATERIA_GRUPO_SESION1`
    FOREIGN KEY (`MAESTRO_MATERIA_GRUPO_SESION_ID` )
    REFERENCES `siec`.`TR_MAESTRO_MATERIA_GRUPO_SESION` (`MAESTRO_MATERIA_GRUPO_SESION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_TR_ALUMNOS1`
    FOREIGN KEY (`ALUMNOS_ID` )
    REFERENCES `siec`.`TR_ALUMNOS` (`ALUMNOS_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TR_EVALUACION_ACUMULATIVA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_EVALUACION_ACUMULATIVA` (
  `EVALUACION_ACUMULATIVA_ID` INT NOT NULL AUTO_INCREMENT ,
  `PARCIAL` INT NULL ,
  `CALIFICACION` INT NULL ,
  PRIMARY KEY (`EVALUACION_ACUMULATIVA_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siec`.`TR_EVALUACION_PARCIAL_ACUMULATIVA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `siec`.`TR_EVALUACION_PARCIAL_ACUMULATIVA` (
  `EVALUACION_PARCIAL_ACUMULATIVA_ID` INT NOT NULL AUTO_INCREMENT ,
  `EVALUACION_PARCIAL_ID` INT NOT NULL ,
  `EVALUACION_ACUMULATIVA_ID` INT NOT NULL ,
  PRIMARY KEY (`EVALUACION_PARCIAL_ACUMULATIVA_ID`) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_PARCIAL1` (`EVALUACION_PARCIAL_ID` ASC) ,
  INDEX `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_ACUMULATIVA1` (`EVALUACION_ACUMULATIVA_ID` ASC) ,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_PARCIAL1`
    FOREIGN KEY (`EVALUACION_PARCIAL_ID` )
    REFERENCES `siec`.`TR_EVALUACION_PARCIAL` (`EVALUACION_PARCIAL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TR_EVALUACION_PARCIAL_ACUMULATIVA_TR_EVALUACION_ACUMULATIVA1`
    FOREIGN KEY (`EVALUACION_ACUMULATIVA_ID` )
    REFERENCES `siec`.`TR_EVALUACION_ACUMULATIVA` (`EVALUACION_ACUMULATIVA_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
